FROM ruby:2.3.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /sms_campaign
WORKDIR /sms_campaign
ADD Gemfile /sms_campaign/Gemfile
ADD Gemfile.lock /sms_campaign/Gemfile.lock
RUN bundle install
ADD . /sms_campaign
CMD bundle exec sidekiq